### ISSUE TITLE
PAT KEY is not working

### ISSUE THREAD

**Issue by cyrillupstream** [Chinchilla-Software-Com/HubSpot.NET#31] opened 2024-05-15 02:14 UTC
An unhandled exception occurred while processing the request.
HubSpotException: Error from HubSpot, Response = {"status":"error","message":"This hapikey doesn't exist.","correlationId":"b38e08ac-c201-4f44-8a56-57a4bc3ce950"}
HubSpot.NET.Core.HubSpotBaseClient.SendRequest(string path, Method method, string json)

**Comment by cdmdotnet** [comment] 2024-05-20 06:33
duplicate of #29

**Closed as completed by cdmdotnet** 2024-05-20 06:33 UTC
